#ifndef _HBRIDGE_CONFIG_H
#define _HBRIDGE_CONFIG_H

#define HBRIDGE_R0_PORT GPIO_PORTA
#define HBRIDGE_R0_PIN GPIO_PIN5
#define HBRIDGE_R1_PORT GPIO_PORTA
#define HBRIDGE_R1_PIN GPIO_PIN5

#define HBRIDGE_L0_PORT GPIO_PORTC
#define HBRIDGE_L0_PIN GPIO_PIN6
#define HBRIDGE_L1_PORT GPIO_PORTC
#define HBRIDGE_L1_PIN GPIO_PIN6

#endif