#ifndef _HBRIDGE_INTERFACE_H
#define _HBRIDGE_INTERFACE_H

void HBRIDGE_vidInit(void);
void HBRIDGE_vidControl(u8 u8Command);

#define HBRIDGE_COMMAND_BOTH_FORWARD 0
#define HBRIDGE_COMMAND_BOTH_BACKWARD 1
#define HBRIDGE_COMMAND_BOTH_STOP 2
#define HBRIDGE_COMMAND_RIGHT_FORWARD 3
#define HBRIDGE_COMMAND_RIGHT_BACKWARD 4
#define HBRIDGE_COMMAND_LEFT_FORWARD 5
#define HBRIDGE_COMMAND_LEFT_BACKWARD 6

#endif