#include "STD_TYPES.h"
#include "Macros.h"
#include "GPIO_interface.h"
#include "SevenSegment_interface.h"

u8 num[10] = {0b00111111,
							0b00000110,
							0b01011011,
							0b01001111,
							0b01100110,
							0b01101101,
							0b01111101,
							0b00000111,
							0b01111111,
							0b01101111};

void SevenSegment_vidInit(void)
{
	/*SevenSegment 1*/
	GPIO_vidSetPinDigEnable(DIS1_SEGMENT_A_PORT,DIS1_SEGMENT_A_PIN,GPIO_DEN_SET);
	GPIO_vidSetPinDirection(DIS1_SEGMENT_A_PORT,DIS1_SEGMENT_A_PIN,GPIO_OUTPUT);
	
	GPIO_vidSetPinDigEnable(DIS1_SEGMENT_B_PORT,DIS1_SEGMENT_B_PIN,GPIO_DEN_SET);
	GPIO_vidSetPinDirection(DIS1_SEGMENT_B_PORT,DIS1_SEGMENT_B_PIN,GPIO_OUTPUT);
	
	GPIO_vidSetPinDigEnable(DIS1_SEGMENT_C_PORT,DIS1_SEGMENT_C_PIN,GPIO_DEN_SET);
	GPIO_vidSetPinDirection(DIS1_SEGMENT_C_PORT,DIS1_SEGMENT_C_PIN,GPIO_OUTPUT);
	
	GPIO_vidSetPinDigEnable(DIS1_SEGMENT_D_PORT,DIS1_SEGMENT_D_PIN,GPIO_DEN_SET);
	GPIO_vidSetPinDirection(DIS1_SEGMENT_D_PORT,DIS1_SEGMENT_D_PIN,GPIO_OUTPUT);
	
	GPIO_vidSetPinDigEnable(DIS1_SEGMENT_E_PORT,DIS1_SEGMENT_E_PIN,GPIO_DEN_SET);
	GPIO_vidSetPinDirection(DIS1_SEGMENT_E_PORT,DIS1_SEGMENT_E_PIN,GPIO_OUTPUT);
	
	GPIO_vidSetPinDigEnable(DIS1_SEGMENT_F_PORT,DIS1_SEGMENT_F_PIN,GPIO_DEN_SET);
	GPIO_vidSetPinDirection(DIS1_SEGMENT_F_PORT,DIS1_SEGMENT_F_PIN,GPIO_OUTPUT);
	
	GPIO_vidSetPinDigEnable(DIS1_SEGMENT_G_PORT,DIS1_SEGMENT_G_PIN,GPIO_DEN_SET);
	GPIO_vidSetPinDirection(DIS1_SEGMENT_G_PORT,DIS1_SEGMENT_G_PIN,GPIO_OUTPUT);
	
	GPIO_vidSetPinDigEnable(DIS1_SEGMENT_U_PORT,DIS1_SEGMENT_U_PIN,GPIO_DEN_SET);
	GPIO_vidSetPinDirection(DIS1_SEGMENT_U_PORT,DIS1_SEGMENT_U_PIN,GPIO_OUTPUT);
	
	/*SevenSegment 2*/
	
	
	
	
}

void SevenSegment1_vidWriteDigit(u8 u8Digit)
{
	u8 number = num[u8Digit];
	GPIO_vidSetPinValue(DIS1_SEGMENT_A_PORT,DIS1_SEGMENT_A_PIN,GET_BIT(number,0));
	GPIO_vidSetPinValue(DIS1_SEGMENT_B_PORT,DIS1_SEGMENT_B_PIN,GET_BIT(number,1));
	GPIO_vidSetPinValue(DIS1_SEGMENT_C_PORT,DIS1_SEGMENT_C_PIN,GET_BIT(number,2));
	GPIO_vidSetPinValue(DIS1_SEGMENT_D_PORT,DIS1_SEGMENT_D_PIN,GET_BIT(number,3));
	GPIO_vidSetPinValue(DIS1_SEGMENT_E_PORT,DIS1_SEGMENT_E_PIN,GET_BIT(number,4));
	GPIO_vidSetPinValue(DIS1_SEGMENT_F_PORT,DIS1_SEGMENT_F_PIN,GET_BIT(number,5));
	GPIO_vidSetPinValue(DIS1_SEGMENT_G_PORT,DIS1_SEGMENT_G_PIN,GET_BIT(number,6));
	GPIO_vidSetPinValue(DIS1_SEGMENT_U_PORT,DIS1_SEGMENT_U_PIN,GET_BIT(number,7));
}

void SevenSegment2_vidWriteDigit(u8 u8Digit)
{

}