#ifndef _SEVENSEGMENT_INTERFACE_H
#define _SEVENSEGMENT_INTERFACE_H

void SevenSegment_vidInit(void);
void SevenSegment1_vidWriteDigit(u8 u8DigitCpy);
void SevenSegment2_vidWriteDigit(u8 u8DigitCpy);
void SevenSegment_vidWriteMultiDigit(u8 u8NumberCpy);
/*PORTs definitions*/
/*Display 1*/
#define DIS1_SEGMENT_A_PORT GPIO_PORTA
#define DIS1_SEGMENT_B_PORT GPIO_PORTA
#define DIS1_SEGMENT_C_PORT GPIO_PORTA
#define DIS1_SEGMENT_D_PORT GPIO_PORTA
#define DIS1_SEGMENT_E_PORT GPIO_PORTA
#define DIS1_SEGMENT_F_PORT GPIO_PORTA
#define DIS1_SEGMENT_G_PORT GPIO_PORTA
#define DIS1_SEGMENT_U_PORT GPIO_PORTA
/*Display 2*/
#define DIS2_SEGMENT_A_PORT GPIO_PORTB
#define DIS2_SEGMENT_B_PORT GPIO_PORTB
#define DIS2_SEGMENT_C_PORT GPIO_PORTB
#define DIS2_SEGMENT_D_PORT GPIO_PORTB
#define DIS2_SEGMENT_E_PORT GPIO_PORTB
#define DIS2_SEGMENT_F_PORT GPIO_PORTB
#define DIS2_SEGMENT_G_PORT GPIO_PORTB
#define DIS2_SEGMENT_U_PORT GPIO_PORTB

/*PINs definitions*/
/*Display 1*/
#define DIS1_SEGMENT_A_PIN GPIO_PIN0
#define DIS1_SEGMENT_B_PIN GPIO_PIN1
#define DIS1_SEGMENT_C_PIN GPIO_PIN2
#define DIS1_SEGMENT_D_PIN GPIO_PIN3
#define DIS1_SEGMENT_E_PIN GPIO_PIN4
#define DIS1_SEGMENT_F_PIN GPIO_PIN5
#define DIS1_SEGMENT_G_PIN GPIO_PIN6
#define DIS1_SEGMENT_U_PIN GPIO_PIN7

/*Display 2*/
#define DIS2_SEGMENT_A_PIN GPIO_PIN0
#define DIS2_SEGMENT_B_PIN GPIO_PIN1
#define DIS2_SEGMENT_C_PIN GPIO_PIN8
#define DIS2_SEGMENT_D_PIN GPIO_PIN9
#define DIS2_SEGMENT_E_PIN GPIO_PIN10
#define DIS2_SEGMENT_F_PIN GPIO_PIN5
#define DIS2_SEGMENT_G_PIN GPIO_PIN6
#define DIS2_SEGMENT_U_PIN GPIO_PIN7
#endif
