#ifndef _ESEVENSEGMENT_INTERFACE_H
#define _ESEVENSEGMENT_INTERFACE_H

void ESevenSegment_vidInit(void);
void ESevenSegment1_vidWriteDigit(u8 u8DigitCpy);
void ESevenSegment2_vidWriteDigit(u8 u8DigitCpy);
void ESevenSegment_vidWriteMultiDigit(u8 u8NumberCpy);
/*PORTs definitions*/
/*Display 1*/
#define DIS1_SEGMENT_A_PORT MDIO_PORTA
#define DIS1_SEGMENT_B_PORT MDIO_PORTA
#define DIS1_SEGMENT_C_PORT MDIO_PORTA
#define DIS1_SEGMENT_D_PORT MDIO_PORTA
#define DIS1_SEGMENT_E_PORT MDIO_PORTA
#define DIS1_SEGMENT_F_PORT MDIO_PORTA
#define DIS1_SEGMENT_G_PORT MDIO_PORTA
#define DIS1_SEGMENT_U_PORT MDIO_PORTA
/*Display 2*/
#define DIS2_SEGMENT_A_PORT MDIO_PORTB
#define DIS2_SEGMENT_B_PORT MDIO_PORTB
#define DIS2_SEGMENT_C_PORT MDIO_PORTB
#define DIS2_SEGMENT_D_PORT MDIO_PORTB
#define DIS2_SEGMENT_E_PORT MDIO_PORTB
#define DIS2_SEGMENT_F_PORT MDIO_PORTB
#define DIS2_SEGMENT_G_PORT MDIO_PORTB
#define DIS2_SEGMENT_U_PORT MDIO_PORTB

/*PINs definitions*/
/*Display 1*/
#define DIS1_SEGMENT_A_PIN MDIO_PIN0
#define DIS1_SEGMENT_B_PIN MDIO_PIN1
#define DIS1_SEGMENT_C_PIN MDIO_PIN2
#define DIS1_SEGMENT_D_PIN MDIO_PIN3
#define DIS1_SEGMENT_E_PIN MDIO_PIN4
#define DIS1_SEGMENT_F_PIN MDIO_PIN5
#define DIS1_SEGMENT_G_PIN MDIO_PIN6
#define DIS1_SEGMENT_U_PIN MDIO_PIN7

/*Display 2*/
#define DIS2_SEGMENT_A_PIN MDIO_PIN0
#define DIS2_SEGMENT_B_PIN MDIO_PIN1
#define DIS2_SEGMENT_C_PIN MDIO_PIN2
#define DIS2_SEGMENT_D_PIN MDIO_PIN3
#define DIS2_SEGMENT_E_PIN MDIO_PIN4
#define DIS2_SEGMENT_F_PIN MDIO_PIN5
#define DIS2_SEGMENT_G_PIN MDIO_PIN6
#define DIS2_SEGMENT_U_PIN MDIO_PIN7
#endif
